//
//  ClipboardConcealedTypeTests.swift
//  SnipsterTests
//

import XCTest
@testable import Snipster

/// Tests the de-facto `org.nspasteboard.*` "don't record me" marker-type
/// detection used to keep password-manager copies out of clipboard history.
/// Exercised as a pure `[String] -> Bool` check, with no real `NSPasteboard`
/// involved.
final class ClipboardConcealedTypeTests: XCTestCase {

    func testPlainTextTypesAreNotDoNotRecord() {
        XCTAssertFalse(ClipboardHistoryService.isDoNotRecord(types: ["public.utf8-plain-text"]))
    }

    func testConcealedTypeMarkerIsDetected() {
        XCTAssertTrue(ClipboardHistoryService.isDoNotRecord(
            types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]
        ))
    }

    func testTransientTypeMarkerIsDetected() {
        XCTAssertTrue(ClipboardHistoryService.isDoNotRecord(
            types: ["public.utf8-plain-text", "org.nspasteboard.TransientType"]
        ))
    }

    func testAutoGeneratedTypeMarkerIsDetected() {
        XCTAssertTrue(ClipboardHistoryService.isDoNotRecord(
            types: ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"]
        ))
    }

    func testEmptyTypesListIsNotDoNotRecord() {
        XCTAssertFalse(ClipboardHistoryService.isDoNotRecord(types: []))
    }
}
