//
//  ClipboardHistoryService.swift
//  Snipster
//

import AppKit
import Combine

/// Watches the system pasteboard and keeps a bounded, in-memory-only history
/// of recent copies. Nothing here is ever written to disk — the history is
/// gone the moment Snipster quits, in addition to whatever auto-clear
/// schedule the user picks. The only way to keep something permanently is to
/// promote it to a real snippet.
@MainActor
final class ClipboardHistoryService: NSObject, ObservableObject {
    static let shared = ClipboardHistoryService()

    private static let enabledKey = "snipster.clipboardHistory.enabled"
    private static let limitKey = "snipster.clipboardHistory.limit"
    private static let wipeIntervalKey = "snipster.clipboardHistory.wipeInterval"

    /// How often to poll `NSPasteboard.general.changeCount`. There is no
    /// notification-based API for pasteboard changes, so polling is the only
    /// option (matches the approach every other macOS clipboard manager uses).
    private static let pollInterval: TimeInterval = 0.5

    /// How long to ignore pasteboard changes after `suppressBriefly()` is
    /// called. Must comfortably span TextExpansionMonitor's swap-then-restore
    /// (restore happens 0.1s after the swap) plus at least one full poll tick,
    /// so a poll can never land inside the transient window.
    nonisolated private static let defaultSuppressDuration: TimeInterval = 0.6

    /// De-facto community convention (used by 1Password, Bitwarden, and other
    /// clipboard managers) for marking pasteboard content as "don't record
    /// me." There is no official Apple API for this.
    nonisolated private static let doNotRecordTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    enum WipeInterval: String, CaseIterable, Identifiable, Codable {
        case never, hourly, daily, weekly

        var id: String { rawValue }

        var label: String {
            switch self {
            case .never: return "Never"
            case .hourly: return "Hourly"
            case .daily: return "Daily"
            case .weekly: return "Weekly"
            }
        }

        var seconds: TimeInterval? {
            switch self {
            case .never: return nil
            case .hourly: return 3600
            case .daily: return 86400
            case .weekly: return 604800
            }
        }
    }

    @Published var entries: [ClipboardHistoryEntry] = []

    @Published var isEnabled: Bool {
        didSet {
            UserDefaults.standard.set(isEnabled, forKey: Self.enabledKey)
            if isEnabled {
                startPolling()
            } else {
                stopPolling()
            }
        }
    }

    @Published var historyLimit: Int {
        didSet {
            UserDefaults.standard.set(historyLimit, forKey: Self.limitKey)
            buffer.capacity = historyLimit
            buffer.trim()
            syncPublishedState()
        }
    }

    @Published var wipeInterval: WipeInterval {
        didSet {
            UserDefaults.standard.set(wipeInterval.rawValue, forKey: Self.wipeIntervalKey)
            rescheduleWipeTimer()
        }
    }

    private var buffer: ClipboardHistoryBuffer
    private var pollTimer: Timer?
    private var wipeTimer: Timer?
    private var lastChangeCount: Int

    // Thread-safe mirror of `buffer.entries`' content, so `historyEntry(back:)`
    // can be called `nonisolated` from `SnippetVariableProcessor` (a
    // `nonisolated Sendable` singleton) without crossing back onto the
    // main actor.
    private let snapshotLock = NSLock()
    nonisolated(unsafe) private var _snapshot: [String] = []

    // `suppressUntil` needs to be settable from `TextExpansionMonitor`'s
    // `nonisolated` paste-simulation code (which runs inside a plain
    // `DispatchQueue.main.async` closure the compiler doesn't statically know
    // is on the main actor), so it's guarded by its own lock rather than
    // being MainActor-isolated storage.
    private let suppressLock = NSLock()
    nonisolated(unsafe) private var _suppressUntil: Date?

    private override init() {
        let defaults = UserDefaults.standard
        isEnabled = defaults.object(forKey: Self.enabledKey) as? Bool ?? true
        let limit = defaults.object(forKey: Self.limitKey) as? Int ?? 30
        historyLimit = limit
        wipeInterval = (defaults.string(forKey: Self.wipeIntervalKey).flatMap(WipeInterval.init(rawValue:))) ?? .daily
        buffer = ClipboardHistoryBuffer(capacity: limit)
        lastChangeCount = NSPasteboard.general.changeCount
        super.init()

        if isEnabled {
            startPolling()
        }
        rescheduleWipeTimer()
    }

    // MARK: - Polling

    private func startPolling() {
        guard pollTimer == nil else { return }
        pollTimer = Timer.scheduledTimer(withTimeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkPasteboard()
            }
        }
    }

    private func stopPolling() {
        pollTimer?.invalidate()
        pollTimer = nil
    }

    private func checkPasteboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        if let suppressUntil = readSuppressUntil(), Date() < suppressUntil {
            return
        }

        guard !isDoNotRecord(pasteboard) else { return }
        guard let string = pasteboard.string(forType: .string) else { return }

        if buffer.insert(string, at: Date()) {
            syncPublishedState()
        }
    }

    private func isDoNotRecord(_ pasteboard: NSPasteboard) -> Bool {
        let types = pasteboard.types?.map(\.rawValue) ?? []
        return Self.isDoNotRecord(types: types)
    }

    /// Pure marker-type check, extracted so it's testable without a real pasteboard.
    nonisolated static func isDoNotRecord(types: [String]) -> Bool {
        !doNotRecordTypes.isDisjoint(with: types)
    }

    // MARK: - Suppression (used by TextExpansionMonitor's transient paste swap)

    /// Called from `TextExpansionMonitor`'s `nonisolated` paste-simulation code,
    /// which runs inside a plain `DispatchQueue.main.async` closure — not
    /// statically MainActor-isolated to the compiler — so this must be safely
    /// callable from any thread.
    nonisolated func suppressBriefly(for duration: TimeInterval = ClipboardHistoryService.defaultSuppressDuration) {
        suppressLock.lock()
        _suppressUntil = Date().addingTimeInterval(duration)
        suppressLock.unlock()
    }

    private func readSuppressUntil() -> Date? {
        suppressLock.lock()
        defer { suppressLock.unlock() }
        return _suppressUntil
    }

    // MARK: - Manual actions

    func clearNow() {
        buffer.clear()
        syncPublishedState()
    }

    // MARK: - Auto-clear scheduling

    private func rescheduleWipeTimer() {
        wipeTimer?.invalidate()
        wipeTimer = nil

        guard let seconds = wipeInterval.seconds else { return }
        wipeTimer = Timer.scheduledTimer(withTimeInterval: seconds, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.clearNow()
            }
        }
    }

    // MARK: - State sync

    private func syncPublishedState() {
        entries = buffer.entries
        snapshotLock.lock()
        _snapshot = buffer.entries.map(\.content)
        snapshotLock.unlock()
    }

    // MARK: - Cross-actor read for SnippetVariableProcessor

    /// Returns the content of the `n`-th most recent history entry (1-based,
    /// most-recent-first). `nonisolated` so `SnippetVariableProcessor` — a
    /// `nonisolated Sendable` singleton — can call it synchronously without
    /// actor-hopping.
    nonisolated func historyEntry(back n: Int) -> String? {
        snapshotLock.lock()
        defer { snapshotLock.unlock() }
        guard n >= 1, n <= _snapshot.count else { return nil }
        return _snapshot[n - 1]
    }
}
